name: Focused Test

on: [pull_request]

jobs:
  focused-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - uses: actions/checkout@v4
      - run: go tool ginkgo unfocus && test -z "$(git status -s)"

